#服务器配置
server:
 port: 8080

#数据库配置
jdbc:
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/jianshu?useUnicode=true&characterEncoding=utf8
  username: root
  password: root
  maxActive: 2335
  maxIdel: 120
  maxWait: 100

spider:
  website: http://www.jianshu.com
  #千赞专题ID
  myCollectionId: 032a478c3dbf
  collectionIds: 723de9bac3cd,bDHhpK,72c6094dbb37,3sT4qY,e8fd7797561f,vHz3Uc,yD9GAd,xYuZYD,9b741cc04b69,fcd7a62be697,c49f14a01a84,e2XTpa,qQB2Zn,RfYyQj,NEt52a,GQ5FAs,2f0905cd646b,5719523181cc,5e02b664e2af,566fa0025d60,1hjajt,RfYyQj,MZp7Ey,70b8514fb442,vHz3Uc,GQ5FAs,avQwgf,20f7f4031550,Jgq3Wc,e2XTpa,xYuZYD,YZRvCb,f6b4ca4bb891,dqfRwQ,8fQvXW,8c92f845cd4d,sqpDaz,yD9GAd,3063e24c8622,Df7njb,e50258a6a44b,qQB2Zn,e7d2d4045b36,cc7808b775b4,3063e24c8622,e50258a6a44b,qQB2Zn,e7d2d4045b36,cc7808b775b4,ef51d47f492d,8d7b3b5f0758,94ca3dfcad65,ff4767b463f1,8b493334965e,5AUzod,snqjhw,7b2be866f564,BATtWp,0856231c8e98,b591324d6443,un8RTj,NEt52a,28d9b538c739,2mvgxp,qqfxgN,wpPRDY,2b21469fd2a0,deae553d5b68,a06a9ce0ff21,uWzdYC,59560508f641,cf616f06b3b8,02fa64a127d8,6565d08a24b3,032a478c3dbf
  threadSize: 100